---
# tasks file for post
- name: install dhcpcd
  apt:
    name: dhcpcd

- name: Insert/Update wlan0 configuration stanza in /etc/dhcpcd.conf
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface wlan0
      static ip_address=192.168.255.1/24
      static routers=192.168.3.1
      static domain_name_servers=8.8.8.8 192.168.3.1

- name: start dhcpcd
  ansible.builtin.service:
    name: dhcpcd
    enabled: yes
    state: restarted
