---
# tasks file for hostap
- name: install hostapd
  apt:
    name: hostapd

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: hostapd.conf
    dest: /etc/hostapd/hostapd.conf

- name: edit /etc/default/hostapd
  ansible.builtin.lineinfile:
    path: /etc/default/hostapd
    regexp: '^DAEMON_CONF='
    line: DAEMON_CONF="/etc/hostapd/hostapd.conf"

- name: start hostapd
  ansible.builtin.service:
    name: hostapd
    enabled: yes
    state: restarted

- name: edit /etc/sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward=1'
    line: net.ipv4.ip_forward=1
