---
# tasks file for pre
- name: Set timezone to '{{ TZ }}'
  timezone:
    name: '{{ TZ }}'

- name: install chrony
  apt:
    name: chrony

- name: start chrony
  ansible.builtin.service:
    name: chrony
    enabled: yes
    state: restarted

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
